swagger: "2.0"
info:
  description: "Schachfish is a chess engine for querying moves and board evaluations"
  version: "1.0.0"
  title: "Schachfish-Api"
host: "petstore.swagger.io"
basePath: "/api"
tags:
- name: "move"
  description: "legal moves"
- name: "evaluation"
  description: "value of board state"
schemes:
- "https"
- "http"
paths:
  /moves:
    post:
      tags:
      - "move"
      summary: "get list of legal moves from board state"
      operationId: "getLegalMovesFromBoardState"
      parameters:
      - in: "body"
        name: "boardState"
        description: "list of pieces and positions / castling information"
        required: true
        schema: 
          $ref: "#/definitions/BoardState"
      responses:
        "200":
          description: "list of legal moves"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/LegalMove"
  /evaluate:
    post:
      tags:
      - "evaluation"
      summary: "get an evaluation of the board"
      operationId: "getBoardEvaluation"
      parameters:
      - in: "body"
        name: "boardState"
        description: "list of pieces and positions / castling information"
        required: true
        schema: 
          $ref: "#/definitions/BoardState"
      responses:
        "200":
          description: "board evaluation"
          schema:
            $ref: "#/definitions/BoardEvaluation"

definitions:
  BoardState:
    type: "object"
    properties:
      blackStatus:
        type: "object"
        $ref: "#/definitions/ColourStatus"
      whiteStatus:
        type: "object"
        $ref: "#/definitions/ColourStatus"
  ColourStatus:
    type: "object"
    properties:
      canCastleKingSide:
        type: "boolean"
      canCastleQueenSide:
        type: "boolean"
      enPassant:
        type: "object"
        properties:
          possible:
            type: "boolean"
          position:
            $ref: "#/definitions/Position"
      Pieces:
        type: "array"
        items:
          $ref: "#/definitions/Piece"
  LegalMove:
    type: "object"
    properties:
      text:
        type: "string"
  BoardEvaluation:
    type: "object"
    properties:
      score:
        type: "integer"
        format: "int64"
  Piece:
    type: "object"
    properties:
      position:
        $ref: "#/definitions/Position"
      name:
        type: "string"
        $ref: "#/definitions/PieceName"
  PieceName:
    type: "string"
    enum:
    - "King"
    - "Queen"
    - "Rook"
    - "Bishop"
    - "Knight"
    - "Pawn"
  Position:
    type: "object"
    properties:
      x:
        type: "integer"
        format: "int64"
      y:
        type: "integer"
        format: "int64"